spring:
  datasource:
    url: jdbc:h2:mem:riskwatchdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

risk:
  thresholds:
    amount: 100000
    velocity:
      limit: 3
      window-minutes: 2
